name: gnr_project_env
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu126
      - torch==2.7.1
      - torchvision==0.22.1
      - vllm @ https://github.com/vllm-project/vllm/releases/download/v0.10.0/vllm-0.10.0+cu126-cp38-abi3-manylinux1_x86_64.whl
      - transformers>=4.53.2,<5.0
      - huggingface_hub>=0.33.0,<1.0
      - pillow==10.4.0
      - pandas==2.2.3
      - jupyter==1.1.1
      - nbconvert==7.16.4
